### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by chukie-clt** [bitfocus/companion-module-colorlight-processor#3]
@josephdadams  Hi, Joseph: 
    We modified some issues and submitted the code to the "main" branch for testing. please check and add this to your final build.
Thanks a lot!

**Comment by josephdadams** [comment]
You need to version bump package.json to a new version, like `1.0.2` for example. And then preferably tag a release like I did of `1.0.1` for you. Create it from the main branch.

**Comment by chukie-clt** [comment]
@josephdadams Hi, Joseph:

**Comment by chukie-clt** [comment]
@josephdadams  Hi, Joseph:
Excuse me, we already released v1.0.2 yesterday. Why didn't we see the latest version in today's Bitfocus Companion software (BETA 3.2.0+6425)?

**Comment by josephdadams** [comment]
Because it’s a manual process after tagging a release to push it to the betas and you just now asked me?

**Comment by chukie-clt** [comment]
Just entered an error. When can I see the latest version because there are customers who need it? thanks!

**Comment by chukie-clt** [comment]
@josephdadams Please help me update the latest v1.0.2 version to the Companion software.
Thank you very much！

**Comment by josephdadams** [comment]
The proper procedure is to request this in #module-development on the Bitfocus slack channel. I will do it for you this time but please join the community there because there are others who can help with this process also and that is where everyone else makes their requests currently. Thanks!

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-bundled-modules/actions/runs/6560851267
